### PR TITLE
add test cases for LIST api

### PR DESCRIPTION
**Pull request by annelai**

### CODE REVIEW

**Comment by jaewhyun** [comment]
@annelai how should we fix this?

**Comment by gau820827** [comment]
Hey @annelai @katydid98 @jaewhyun here's my thought -- I don't think it's a good idea to create Recommendation objects in Setup() function. In different test cases, we need to define different behaviors and different results we expect. Sometimes we want to add different kinds of recommendations for testing, sometimes we want to test whether an action on an empty database returns 404 normally. Therefore to set up different recommendation database for each scenario would be easier for both testing and the readability of test codes.

**Comment by katydid98** [comment]
@annelai @jaewhyun @gau820827 - after working on the Update an Issue recommendation last night, I would agree with Yi.  It doesn't make our code look as clean, but it does allow us to write our test cases in isolation without thinking about the impact on someone else's test.

**Comment by jaewhyun** [comment]
@katydid98 what is Update an Issue recommendation?

**Comment by jaewhyun** [comment]
@katydid98 @gau820827 I guess that makes sense! That being said the professor does initialize two recommendations in setup in his example. Why is that? I think that's why @annelai put those there.

**Comment by katydid98** [comment]
@jaewhyun Update a Recommendation is one of the APIs we have to write.  It's one of the outstanding issues we still have in queue.... Regarding the test cases, the professor is able to put it in setUp because he's writing all the test cases himself, but our structure is that we are breaking it up so we have to be able to each write code independent of each other.   @annelai @gau820827

**Comment by annelai** [comment]
After reading your discussion, I agree it's better to break them into different cases for now. I'll fix this today.

**Pull request merged**
