### PR TITLE
Issue14 - Created a draft for README- PLEASE REVIEW

### PR DESCRIPTION
**Pull request by katydid98**
@jaewhyun @gau820827 @annelai - I updated our README file.  Could use team's suggestions on how we can improve by adding more details.  Please add your thoughts.

### CODE REVIEW

**Comment by katydid98** [comment]
@jaewhyun Thanks Jae! What do you mean by code block?

**Comment by jaewhyun** [comment]
I see it's already like that!! my bad. I think it looks good

**Comment by katydid98** [comment]
Please click the view button at top to see true display

screen shot 2018-03-06 at 2 05 17 am

**Comment by jaewhyun** [comment]
let's add our travis ci and codecov badge!

**Comment by jaewhyun** [comment]
[codecov](https://codecov.io/gh/NYU-DevOps-S18-Recommendations/recommendations)

**Comment by jaewhyun** [comment]
[Build Status](https://travis-ci.org/NYU-DevOps-S18-Recommendations/recommendations)

**Comment by jaewhyun** [comment]
but the professor doesn't have the badge in his readme for RESTful Flask README so I'm not sure

**Comment by katydid98** [comment]
Good idea!! he has it in his lab-flask-tdd. Let me review how to do that. =)

**Comment by gau820827** [comment]
Maybe we can add this before the last paragraph

## Manually running the Tests

Run the tests using `nosetests` and `coverage`

    $ nosetests
    $ coverage report -m --include=server.py

**Comment by jaewhyun** [comment]
Is that necessary for the README file though?

**Comment by katydid98** [comment]
Professor has it in his lab-flask-tdd so I think it's a good idea!

**Comment by annelai** [comment]
This is so well written! good job @katydid98

**Comment by katydid98** [comment]
@jaewhyun @gau820827 @annelai hey guys - do users of our service actually need instructions for virtual box and vagrant?  I don't quite have the big picture yet, so if they don't, makes sense to delete in the README right?  It made sense that professor had that in lab-flask-tdd and lab-restful..but not for our service... my assumptions.

**Comment by katydid98** [comment]
@gau820827 @annelai @jaewhyun - hey guys, according to the hw specs for README:

"Create a README.md file and make sure that you give instructions on what calls are available and what inputs they expect and how to run and test your code so that users will know how it works."

Can you guys give me suggestions on what we should include to cover the requirement as stated?

**Comment by jaewhyun** [comment]
@katydid98 these are so great!!

**Comment by katydid98** [comment]
@jaewhyun hahah, thank you, thank you.  Sorry if each revision blew up your email.  Each time I pushed, I either saw another mistake or the formatting wouldn't line up so I kept having to re-push to see what it looked like on github.

**Comment by katydid98** [comment]
@jaewhyun hahah!! my bad! my bad!!! good news, i think its done though. just waiting for it to get merged. =)

**Pull request merged**
