### PR TITLE
Issue8 - Added Update a Recommendation

### PR DESCRIPTION
**Pull request by katydid98**
Please review

### CODE REVIEW

**Comment by katydid98** [comment]
@gau820827 okay to merge request?

**Comment by jaewhyun** [comment]
We should wait to merge the pull requests in order though, right?

**Comment by katydid98** [comment]
@jaewhyun good question. idk, is it okay to merge if mine has no conflicts?

**Comment by gau820827** [comment]
I agree with @jaewhyun. From the lecture, we should merge PRs follows the order of creating them.

**Comment by annelai** [comment]
lgtm 👍 I've merged mine so no blocks ahead yours now!

**Pull request merged**
